# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 19:20
from __future__ import unicode_literals
import csv
from django.db import migrations


def load_movies(apps, schema_editor):
    Movie = apps.get_model('recommender_app', 'Movie')
    datafile_PATH = 'u.item'
    with open(datafile_PATH, 'r', encoding='latin-1') as f:
        columns = {'fieldnames': ('movie_id', 'title', 'release_year',
                                  'video_release', 'imdb_link')}
        reader = csv.DictReader(f, **columns, delimiter='|')
        for row in reader:
            m = Movie(id=row['movie_id'], title=row['title'],
                      release_year=row['release_year'],
                      video_release=row['video_release'],
                      imdb_link=row['imdb_link'])
            m.save()


def load_raters(apps, schema_editor):
    Rater = apps.get_model('recommender_app', 'Rater')
    datafile_PATH = 'u.user'
    with open(datafile_PATH, 'r', encoding='latin-1') as f:
        columns = {'fieldnames': ('rater_id', 'age', 'gender', 'job', 'zipcode')}
        reader = csv.DictReader(f, **columns, delimiter='|')
        for row in reader:
            r = Rater(id=row['rater_id'], age=row['age'], gender=row['gender'],
                      job=row['job'], zipcode=row['zipcode'])
            r.save()


def load_ratings(apps, schema_editor):
    Movie = apps.get_model('recommender_app', 'Movie')
    Rater = apps.get_model('recommender_app', 'Rater')
    Rating = apps.get_model('recommender_app', 'Rating')
    datafile_PATH = 'u.data'
    with open(datafile_PATH, 'r', encoding='latin-1') as f:
        columns = {'fieldnames': ('rater_id', 'movie_id', 'rating', 'timestamp')}
        reader = csv.DictReader(f, **columns, delimiter='\t')
        for row in reader:
            m = Movie.objects.get(id=row['movie_id'])
            rater = Rater.objects.get(id=row['rater_id'])
            r = Rating(rating=row['rating'], timestamp=row[ea'timestamp'], movie=m, rater=rater)
            r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_movies),
        migrations.RunPython(load_raters),
        migrations.RunPython(load_ratings),
    ]
